SELECT OPPID AS "Program ID",
OPRL01 AS "RPC 01",
OPRL02 AS "RPC 02",
OPRL03 AS "RPC 03",
OPRL04 AS "RPC 04",
OPRL05 AS "RPC 05",
OPMCU AS "Business unit",
OPMCUS AS "BU subsequent",
OPUSER AS "User ID",
OPARGC AS "Area grouping code",
OPARGV AS "Area grouping value",
OPDL01 AS "Description",
OPCO AS "Company",
OPFLOR AS "Number - floor",
OPFOTY AS "Floor type"
FROM STGODS.F1506


SELECT 
NHADDS AS "State",
NHADDZ AS "Postal code",
NHAM01 AS "Ep unit type",
NHAM02 AS "Amenity code 02",
NHAM03 AS "Amenity code 03",
NHAM04 AS "Amenity code 04",
NHAM05 AS "Amenity code 05",
NHAM06 AS "Amenity code 06",
NHAM07 AS "Amenity code 07",
NHAM08 AS "Amenity code 08",
NHAM09 AS "Amenity code 09",
NHAM10 AS "Amenity code 10",
NHAM11 AS "Amenity code 11",
NHAM12 AS "Amenity code 12",
NHAM13 AS "Amenity code 13",
NHAM14 AS "Amenity code 14",
NHAM15 AS "Amenity code 15",
NHAM16 AS "Amenity code 16",
NHAM17 AS "Amenity code 17",
NHAM18 AS "Amenity code 18",
NHAM19 AS "Amenity code 19",
NHAM20 AS "Amenity code 20",
NHASTD AS "Amount - standard billing",
NHBFRQ AS "Standard billing frequency",
NHCO AS "Company",
NHCTR AS "Country",
NHDL01 AS "Description",
NHDL02 AS "Description 02",
NHDL03 AS "Description 03",
NHDL04 AS "Description 04",
NHDL05 AS "Description 05",
NHDV AS "Date - last vacated",
NHFLOR AS "Number - floor",
NHGLC AS "G/L offset",
NHMART AS "Market rent",
NHMCU AS "Business unit",
NHMCUS AS "Business unit - subsequent",
NHMSTU AS "Master unit",
NHMSUT AS "Master or sub unit",
NHPID AS "Program ID",
NHPORT AS "Potential rent",
NHPRRT AS "Prior month potential rent",
NHRERT AS "Renewal rent",
NHRL01 AS "RPC 01",
NHRL02 AS "RPC 02",
NHRL03 AS "RPC 03",
NHRL04 AS "RPC 04",
NHRL05 AS "RPC 05",
NHUNIT AS "Unit",
NHUPMT AS "Time - last updated",
NHUSER AS "User ID",
NHUST AS "Unit status",
NHUST1 AS "Unit occupancy status",
NHUST2 AS "Unit availability status",
NHUST3 AS "Composite unit status",
NHUST4 AS "Unit held by status",
NHUTTY AS "Unit type",
NHUTUS AS "Unit usage",
FROM STGODS.F1507



SELECT NWMCU AS "Business Unit",
NWFLOR AS "Number - Floor",
NWUNIT AS "Unit",
NWARTY AS "Area Type",
NWARGC AS "Area Grouping Code",
NWARGV AS "Area Grouping Value",
NWDL01 AS "Description",
NWARLL AS "Area Level",
NWSEQ AS "Sequence Number",
NWPMU1 AS "Units",
NWUM AS "Unit of Measure",
NWEFTB AS "Date - Beginning Effective",
NWEFTE AS "Date - Ending Effective",
NWURCD AS "User Reserved Code",
NWURDT AS "User Reserved Date",
NWURAT AS "User Reserved Amount",
NWURAB AS "User Reserved Number",
NWURRF AS "User Reserved Reference",
NWUSER AS "User ID",
NWPID AS "Program ID",
NWUPMJ AS "Date - Updated",
NWUPMT AS "Time - Last Updated",
NWJOBN AS "Work Station ID",
NWENTJ AS "Date - Entered",
NWTORG AS "Transaction Originator"
 FROM STGODS.F1514